config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user, ->(u) { u.type == 'Parent' } do
      root 'pages#parent_dashboard', as: :parent_root
      resources :grades, only: [:index, :show]
    end

    authenticated :user, ->(u) { u.type == 'Teacher' } do
      root 'pages#teacher_dashboard', as: :teacher_root
      resources :students, only: [:show]
      resources :sections, only: [:index, :show] do
        member do
          get :students
          get :add_grade, to: 'sections#add_grade'
          get :show_grades, to: 'sections#show_grades'
          post :create_grades, to: 'sections#create_grades'
        end
      end
    end
    authenticated :user do
      get 'chatrooms/find_or_create', to: 'chatrooms#find_or_create'
      resources :chatrooms, only: [:show, :index, :create] do
        resources :messages, only: [:create]
      end
    end
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

# authenticated :user, ->(u) { u.super_admin? } do
#   root 'companies#index', as: :admin_root
# end
# authenticated :user, ->(u) { !u.super_admin? && u.company.cgu_accepted_at.nil? } do
#   root 'pages#help', as: :starting_root
# end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :course
  belongs_to :student
  # has_one_attached :photo

  validates :grade, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 6 }
  validates :student, uniqueness: { scope: [:course_id, :exam_name], message: "should have only one grade per exam per course" }
  validates :date, presence: true
  validates :exam_name, presence: true
  validate :exam_date_cannot_be_in_the_future

  def exam_date_cannot_be_in_the_future
    errors.add(:date, "can't be in the future") if date.present? && date > Date.today
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  def index
    @parent = current_user
    @student = @parent.student
    @section = @student.section
    @courses = @section.courses
    @student_grades = @student.grades.order(:created_at)
    @latest_grades = @student.grades.order(created_at: :desc).limit(3)

    # Group grades by course
    @grades_by_course = @student_grades.group_by(&:course)

    # max number of grades
    @grades_count_by_course = @grades_by_course.transform_values(&:count)
    @max_grades = @grades_count_by_course.max_by { |_, count| count }.last

    # Calculate averages of each course
    @averages_by_course = {}
    @grades_by_course.each do |course, grades|
      total_grades = grades.length
      total_points = grades.reduce(0) { |sum, grade| sum + grade.grade }
      average_grade = (total_points / total_grades.to_f).round(1)
      formatted_average_grade = sprintf("%.1f", average_grade)
      @averages_by_course[course] = average_grade
    end

    # Calculate averages of course entire class
    @courses = @section.courses
    @grades_by_courses = {}

    @courses.each do |course|
      grades = Grade.where(course: course)
      course_average = grades.average(:grade).round(1)
      formatted_course_grade = sprintf("%.1f", course_average)
      @grades_by_courses[course] = course_average
    end
  end

  def show
    @grade = Grade.find(params[:id])
  end
end

app/views/grades/index.html.erb
<div class="show-classes-container">
  <div class="cards-container d-flex justify-content-around pt-3">
    <h3><%=@student.first_name%>'s Grades</h3>
    <h4>Class : <%=@section.name%></h4>
  </div>

  <div class="show-table-container me-4">
    <div class="tabs">
      <!-- Exemple pour Classroom Students (Assumant que c'est la page index des sections) -->
      <div class="d-flex justify-content-between pe-5">
        <h4>Grades</h4>
        <h4>Averages</h4>
      </div>
    </div>

    <!-- Student list -->
    <div class="student-list d-flex">
      <table class="table table-hover me-2 rounded-table">
        <thead>
          <tr>

            <th>Course Name</th>
            <th colspan="<%= @max_grades %>" class="text-center">Grades</th>
          </tr>
        </thead>

        <tbody>
          <% @grades_by_course.each do |course, grades| %>
            <tr class="text-center">
              <td><i class="<%= course.icon %>"></i> <%= course.name %></td>
              <% grades.each do |grade| %>
                <td class="text-center">
                  <%= link_to grade_path(grade), class: 'text-decoration-none fw-bold', style: 'color: black;' do %>
                    <% case grade.grade %>
                      <% when 1.0..1.4 %>
                        <span class="bg-one text-white p-2 rounded"><%= grade.grade %></span>
                      <% when 1.5..1.9 %>
                        <span class="bg-one-half text-white p-2 rounded"><%= grade.grade %></span>
                      <% when 2.0..2.4 %>
                        <span class="bg-two text-white p-2 rounded"><%= grade.grade %></span>
                      <% when 2.5..2.9 %>
                        <span class="bg-two-half text-white p-2 rounded"><%= grade.grade %></span>
                      <% when 3.0..3.4 %>
                        <span class="bg-three text-white p-2 rounded"><%= grade.grade %></span>
                      <% when 3.5..3.9 %>
                        <span class="bg-three-half text-white p-2 rounded"><%= grade.grade %></span>
                      <% when 4.0..4.4 %>
                        <span class="bg-four text-white p-2 rounded"><%= grade.grade %></span>
                      <% when 4.5..4.9 %>
                        <span class="bg-four-half text-white p-2 rounded"><%= grade.grade %></span>
                      <% when 5.0..5.4 %>
                        <span class="bg-five text-white p-2 rounded"><%= grade.grade %></span>
                      <% when 5.5..5.9 %>
                        <span class="bg-five-half text-white p-2 rounded"><%= grade.grade %></span>
                      <% when 6.0 %>
                        <span class="bg-six text-white p-2 rounded"><%= grade.grade %></span>
                      <% else %>
                        <span class="bg-success text-white p-2 rounded"><%= grade.grade %></span>
                      <% end %>
                  <% end %>
                </td>
              <% end %>
              <% (@max_grades - grades.count).times do %>
                <td></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>

      </table>
      <table class="table table-hover me-1 rounded-table" style="width: 120px;">
        <thead>
          <tr>
            <th>Student</th>
          </tr>
        </thead>

        <tbody>
          <% @averages_by_course.each do |course, formatted_average_grade|%>
            <tr class="text-center">
              <td class="text-center fw-bold"><%=formatted_average_grade %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
      <table class="table table-hover rounded-table" style="width: 120px;">
        <thead>
          <tr class="text-center">
            <th class="text-center">Class </th>
          </tr>
        </thead>
        <tbody>
          <% @grades_by_courses.each do |course, formatted_course_grade|%>
            <tr class="text-center">
              <td class="text-center fw-bold"><%=formatted_course_grade%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
    <div class="show-table-container me-4">
  <h4>Latest Grades</h4>
  <table class="table table-hover rounded-table">
    <thead>
      <tr class="text-center">
        <th class="table-header">Course</th>
        <th class="table-header">Grade</th>
        <th class="table-header">Exam Name</th>
        <th class="table-header">Date Added</th>
        <th class="table-header"></th> <!-- Colonne supplémentaire sans en-tête -->
      </tr>
    </thead>
    <tbody>
      <% @latest_grades.each do |grade| %>
        <tr class="text-center">
          <td><%= grade.course.name %></td>
          <td>
            <%= link_to grade_path(grade), class: 'text-decoration-none fw-bold', style: 'color: black;' do %>
              <% case grade.grade %>
                <% when 1.0 %>
                  <span class="bg-one text-white p-2 rounded"><%= grade.grade %></span>
                <% when 1.5 %>
                  <span class="bg-one-half text-white p-2 rounded"><%= grade.grade %></span>
                <% when 2.0 %>
                  <span class="bg-two text-white p-2 rounded"><%= grade.grade %></span>
                <% when 2.5 %>
                  <span class="bg-two-half text-white p-2 rounded"><%= grade.grade %></span>
                <% when 3.0 %>
                  <span class="bg-three text-white p-2 rounded"><%= grade.grade %></span>
                <% when 3.5 %>
                  <span class="bg-three-half text-white p-2 rounded"><%= grade.grade %></span>
                <% when 4.0 %>
                  <span class="bg-four text-white p-2 rounded"><%= grade.grade %></span>
                <% when 4.5 %>
                  <span class="bg-four-half text-white p-2 rounded"><%= grade.grade %></span>
                <% when 5.0 %>
                  <span class="bg-five text-white p-2 rounded"><%= grade.grade %></span>
                <% when 5.5 %>
                  <span class="bg-five-half text-white p-2 rounded"><%= grade.grade %></span>
                <% when 6.0 %>
                  <span class="bg-six text-white p-2 rounded"><%= grade.grade %></span>
                <% else %>
                  <span class="bg-success text-white p-2 rounded"><%= grade.grade %></span>
              <% end %>
            <% end %>
          </td>
          <td><%= grade.exam_name %></td>
          <td><%= grade.created_at.strftime("%d %b %Y") %></td>
          <td>
            <%= link_to "See grade details", grade_path(grade), class: 'btn btn-outline-primary btn-sm' %> <!-- Lien vers les détails de la note -->
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

</div>

app/views/grades/show.html.erb
<div class="show-classes-container">
  <div class="cards-container d-flex justify-content-center pt-3 ">
    <h3 class = "subtitle">Grade Details</h3>
  </div>
  <div class="show-table-container-grades me-4">
    <div class="tabs">
      <%= link_to 'Back to all grades', grades_path, id: "add-grade-btn" %>
    </div>
    <div class="tabs">
      <div class="student-list mt-3" id="grade-details">
        <table class="table table-hover rounded-table">
          <tbody>
            <tr>
              <th class="text-center grade-th">Course Name</th>
              <td class="text-center"><i class="<%= @grade.course.icon %>"></i> <%=@grade.course.name%></td>
            </tr>
            <tr>
              <th class="text-center grade-th">Teacher Name</th>
              <td class="text-center bg-light"><i class="fas fa-graduation-cap"></i> <%=@grade.course.teacher.first_name%> <%=@grade.course.teacher.last_name%></td>
            </tr>
            <tr>
              <th class="text-center grade-th">Exam Name</th>
              <td class="text-center"><%=@grade.exam_name%></td>
            </tr>
            <tr>
              <th class="text-center grade-th">Exam Date</th>
              <td class="text-center bg-light"><i class="fas fa-calendar-days ms-3"></i> <%=@grade.date.strftime("%B %d, %Y")%></td>
            </tr>
            <tr>
              <th class="text-center grade-th">Grade</th>
              <td class="text-center">
                <% case @grade.grade %>
                  <% when 1.0..1.4 %>
                    <span class="bg-one text-white p-2 rounded"><%= @grade.grade %></span>
                  <% when 1.5..1.9 %>
                    <span class="bg-one-half text-white p-2 rounded"><%= @grade.grade %></span>
                  <% when 2.0..2.4 %>
                    <span class="bg-two text-white p-2 rounded"><%= @grade.grade %></span>
                  <% when 2.5..2.9 %>
                    <span class="bg-two-half text-white p-2 rounded"><%= @grade.grade %></span>
                  <% when 3.0..3.4 %>
                    <span class="bg-three text-white p-2 rounded"><%= @grade.grade %></span>
                  <% when 3.5..3.9 %>
                    <span class="bg-three-half text-white p-2 rounded"><%= @grade.grade %></span>
                  <% when 4.0..4.4 %>
                    <span class="bg-four text-white p-2 rounded"><%= @grade.grade %></span>
                  <% when 4.5..4.9 %>
                    <span class="bg-four-half text-white p-2 rounded"><%= @grade.grade %></span>
                  <% when 5.0..5.4 %>
                    <span class="bg-five text-white p-2 rounded"><%= @grade.grade %></span>
                  <% when 5.5..5.9 %>
                    <span class="bg-five-half text-white p-2 rounded"><%= @grade.grade %></span>
                  <% when 6.0 %>
                    <span class="bg-six text-white p-2 rounded"><%= @grade.grade %></span>
                  <% else %>
                    <span class="bg-success text-white p-2 rounded"><%= @grade.grade %></span>
                <% end %>
              </td>
            </tr>
            <tr>
              <th class="text-center grade-th">Comment</th>
              <td class="bg-light"><em><%=@grade.comment%></em></td>
            </tr>
            <tr>
              <th class="text-center grade-th">Exam files</th>
              <% if @grade.photo.nil? || @grade.photo.empty? %>
                <td>No File</td>
              <%else%>
              <td>
                <a href="<%=@grade.photo%>" target="_blank">view</a>
              </td>
              <%end%>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>