config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user, ->(u) { u.type == 'Parent' } do
      root 'pages#parent_dashboard', as: :parent_root
      resources :grades, only: [:index, :show]
    end

    authenticated :user, ->(u) { u.type == 'Teacher' } do
      root 'pages#teacher_dashboard', as: :teacher_root
      resources :students, only: [:show]
      resources :sections, only: [:index, :show] do
        member do
          get :students
          get :add_grade, to: 'sections#add_grade'
          get :show_grades, to: 'sections#show_grades'
          post :create_grades, to: 'sections#create_grades'
        end
      end
    end
    authenticated :user do
      get 'chatrooms/find_or_create', to: 'chatrooms#find_or_create'
      resources :chatrooms, only: [:show, :index, :create] do
        resources :messages, only: [:create]
      end
    end
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

# authenticated :user, ->(u) { u.super_admin? } do
#   root 'companies#index', as: :admin_root
# end
# authenticated :user, ->(u) { !u.super_admin? && u.company.cgu_accepted_at.nil? } do
#   root 'pages#help', as: :starting_root
# end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :parent, class_name: "Parent"
  belongs_to :teacher, class_name: "Teacher"
  has_many :messages, dependent: :destroy
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show]
  before_action :check_access, only: [:show]

  def show
    @chatroom = Chatroom.find(params[:id])
    @messages = @chatroom.messages.includes(:user).order(created_at: :asc)
    @message = Message.new
    @chatroom.messages.where.not(user_id: current_user.id).update_all(read: true)
  end

  def index
    if current_user.type == "Teacher"
      students = Student.joins(:courses).where(courses: { teacher_id: current_user.id }).distinct
      students = students.sort_by { |student| [student.section_id, student.last_name] }
      @parent_data = students.map do |student|
        parent = student.parent
        next unless parent
        unread_messages = Chatroom.where(teacher_id: current_user.id, parent_id: parent.id).any? { |chatroom| chatroom.messages.where.not(user_id: current_user.id).where(read: false).exists? }
        { parent: parent, unread_messages: unread_messages }
      end.compact
    elsif current_user.type == "Parent"
      student = current_user.student
      if student
        unique_teachers = student.courses.includes(:teacher).map(&:teacher).uniq
        @teacher_data = unique_teachers.map do |teacher|
          unread_messages = Chatroom.where(teacher_id: teacher.id, parent_id: current_user.id).joins(:messages).where(messages: {read: false, user_id: teacher.id}).exists?
          { teacher: teacher, unread_messages: unread_messages }
        end
      end
    end
  end


  def find_or_create
    teacher_id = params[:teacher_id]
    parent_id = params[:parent_id] || current_user.id

    chatroom = Chatroom.find_or_create_by(teacher_id: teacher_id, parent_id: parent_id)
    redirect_to chatroom
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:id])
  end

  def check_access
    unless current_user == @chatroom.parent || current_user == @chatroom.teacher
      redirect_to chatrooms_path, alert: "Vous n'avez pas l'accès à cette chatroom."
    end
  end
end

app/views/chatrooms/index.html.erb
<div class="second-container">
  <h4 class="text-center">Contacts</h4>
  <div class="table-responsive" id="contacts-chatroom">
    <table class="table">
      <thead>
        <tr>
          <% if current_user.type == "Teacher" %>
            <th>Parent's Name</th>
            <th>Student's Name</th>
            <th>Section</th>
            <th></th>
          <% elsif current_user.type == "Parent" %>
            <th>Teacher's  Name</th>
            <th>Courses</th>
            <th>Section</th>
            <th></th>
          <% end %>
        </tr>
      </thead>
        <tbody>
          <% if current_user.type == "Teacher" %>
            <% @parent_data.each do |data| %>
              <% parent = data[:parent] %>
              <% student = parent.student %>
              <% if student.present? %>
                <tr>
                  <td>
                    <%= parent.first_name %> <%= parent.last_name %>
                    <% if data[:unread_messages] %>
                      <i class="fa-regular fa-message text-danger"></i>
                    <% end %>
                  </td>
                  <td><%= student.first_name %> <%= student.last_name %></td>
                  <td><%= student.section.name %></td>
                  <td><%= link_to 'Contact Parent', chatrooms_find_or_create_path(teacher_id: current_user.id, parent_id: parent.id), class: "btn btn-outline-primary" %></td>
                </tr>
              <% end %>
            <% end %>
          <% elsif current_user.type == "Parent" %>
            <% student = current_user.student %>
            <% @teacher_data.each do |data| %>
              <% teacher = data[:teacher] %>
              <tr>
                <td>
                  <%= teacher.first_name %> <%= teacher.last_name %>
                  <% if data[:unread_messages] %>
                        <i class="fa-regular fa-message text-danger"></i>
                  <% end %>
                </td>
                <td><%= teacher.courses.where(section_id: student.section_id).map(&:name).join(", ") %></td>
                <td><%= student.section.name %></td>
                <td><%= link_to 'Contact Teacher', chatrooms_find_or_create_path(teacher_id: teacher.id, parent_id: current_user.id), class: "btn btn-outline-primary" %></td>
              </tr>
            <% end %>
          <% end %>

        </tbody>
    </table>
  </div>
</div>

app/views/chatrooms/show.html.erb
<div class="blur-container">
  <div class="chatroom-container">
    <h2>Schoolink Messenger</h2>

    <div id="messages" class="messages">
      <% @messages.each do |message| %>
        <div class="<%= message.user.type == 'Parent' ? 'message-parent' : 'message-teacher' %>">
          <small><%= message.created_at.strftime("%d/%m/%Y %H:%M") %></small>
          <p>
            <strong><%= message.user.first_name %>:</strong>
            <%= message.content %>
          </p>
        </div>
      <% end %>
    </div>

    <%= form_for [@chatroom, @message], html: { class: "message-form" } do |f| %>
      <div class="field">
        <%= f.text_area :content, class: "text_area" %>
      </div>
      <div class="actions">
        <%= f.submit "Send", class: "submit-button" %>
      </div>
    <% end %>
  </div>
</div>