config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user, ->(u) { u.type == 'Parent' } do
      root 'pages#parent_dashboard', as: :parent_root
      resources :grades, only: [:index, :show]
    end

    authenticated :user, ->(u) { u.type == 'Teacher' } do
      root 'pages#teacher_dashboard', as: :teacher_root
      resources :students, only: [:show]
      resources :sections, only: [:index, :show] do
        member do
          get :students
          get :add_grade, to: 'sections#add_grade'
          get :show_grades, to: 'sections#show_grades'
          post :create_grades, to: 'sections#create_grades'
        end
      end
    end
    authenticated :user do
      get 'chatrooms/find_or_create', to: 'chatrooms#find_or_create'
      resources :chatrooms, only: [:show, :index, :create] do
        resources :messages, only: [:create]
      end
    end
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

# authenticated :user, ->(u) { u.super_admin? } do
#   root 'companies#index', as: :admin_root
# end
# authenticated :user, ->(u) { !u.super_admin? && u.company.cgu_accepted_at.nil? } do
#   root 'pages#help', as: :starting_root
# end

app/views/shared/_body_bootstrap.html.erb
<body>
  <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Schoolink</a>
    <input class="form-control form-control-dark w-50" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link" href="#">Sign out</a>
      </li>
    </ul>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                Dashboard <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
                My classes
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
                Agenda ?...
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                Logout
              </a>
            </li>

          </ul>
        </div>
      </nav>


    </div>
  </div>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
  <script src="../../assets/js/vendor/popper.min.js"></script>
  <script src="../../dist/js/bootstrap.min.js"></script>

  <!-- Icons -->
  <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
  <script>
    feather.replace()
  </script>

  <!-- Graphs -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.1/dist/Chart.min.js"></script>
  <script>
    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        datasets: [{
          data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
          lineTension: 0,
          backgroundColor: 'transparent',
          borderColor: '#007bff',
          borderWidth: 4,
          pointBackgroundColor: '#007bff'
        }]
      },
      options: {
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: false
            }
          }]
        },
        legend: {
          display: false,
        }
      }
    });
  </script>


</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="header">
  <h1>Welcome to My App</h1>
  <%= form_tag do %>
    <%= label_tag :date, "Select a Date:" %>
    <%= text_field_tag :date, nil, class: "datepicker" %>
    <%= submit_tag "Submit" %>
  <% end %>
</div>

app/views/shared/_navbar-top.html.erb
<header class="d-flex header-container">
  <div class="date-container">
    <div class="today-container d-flex align-items-center">
      <%= Time.now.strftime("%d %B, %Y") %> <i class="fa-solid fa-calendar-days ms-3"></i>
    </div>
  </div>

  <div class="nav-top-title flex-start ">
    <% if current_user.type == "Teacher" %>
      <%= link_to teacher_root_path do %>
        <%= image_tag(("logo.png") , :class => "user-img") %>
      <% end %>
    <% end %>

    <% if current_user.type == "Parent" %>
      <%= link_to teacher_root_path do %>
        <%= image_tag(("logo.png") , :class => "user-img ") %>
      <% end %>
    <% end %> <i>Schoolink</i>
  </div>

  <div class="login-details">
    <div class="inbox">Inbox<i class="fa-regular fa-message"></i><%= @unread_messages_count %></div>
    <p class="text-center"><%= current_user.first_name %> <%= current_user.last_name %>
      <div class="user"><%= image_tag(("user.png") , :class => "avatar-img") %><div>
    </p>
  </div>
</header>

app/views/shared/_sidebar.html.erb
<div class="side-nav">
<!--  <div class="user">

        <%# if current_user.type == "Teacher" %>-->
          <%#= link_to teacher_root_path do %>
            <%#= image_tag(("logo.png") , :class => "user-img") %>
          <%# end %>
        <%# end %>
<!---->
        <%# if current_user.type == "Parent" %>
          <%#= link_to teacher_root_path do %>
            <%#= image_tag(("logo.png") , :class => "user-img") %>
          <%# end %>
        <%# end %>
<!--  </div>-->
  <ul>
    <li><%= link_to teacher_root_path do %>
        <%= image_tag("dashboard.png") %>
        <span>Dashboard</span>
      <% end %>
    </li>
    <% if current_user.type == "Teacher" %>
      <li>
        <%= link_to current_user.sections.first do %>
          <%= image_tag("members.png") %>
          <span>Classes</span>
        <% end %>
      </li>
    <% end %>

    <% if current_user.type == "Parent" %>
      <li>
        <%= link_to grades_path do %>
          <%= image_tag("reports.png") %>
          <span>Grades</span>
        <% end %>
      </li>
    <% end %>

<% if current_user.type == "Teacher" && current_user.sections.any? %>
  <li>
    <%= link_to show_grades_section_path(current_user.sections.first) do %>
      <%= image_tag("reports.png") %>
      <span>Grades</span>
    <% end %>
  </li>
<% end %>


   <li>
      <%= link_to chatrooms_path do %>
        <%= image_tag("messages.png") %>
        <span>Communications</span>
      <% end %>
    </li>

    <li>
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
        <%= image_tag("logout.png") %>
        <span>Log out</span>
      <% end %>
    </li>
  </ul>
</div>