config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user, ->(u) { u.type == 'Parent' } do
      root 'pages#parent_dashboard', as: :parent_root
      resources :grades, only: [:index, :show]
    end

    authenticated :user, ->(u) { u.type == 'Teacher' } do
      root 'pages#teacher_dashboard', as: :teacher_root
      resources :students, only: [:show]
      resources :sections, only: [:index, :show] do
        member do
          get :students
          get :add_grade, to: 'sections#add_grade'
          get :show_grades, to: 'sections#show_grades'
          post :create_grades, to: 'sections#create_grades'
        end
      end
    end
    authenticated :user do
      get 'chatrooms/find_or_create', to: 'chatrooms#find_or_create'
      resources :chatrooms, only: [:show, :index, :create] do
        resources :messages, only: [:create]
      end
    end
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

# authenticated :user, ->(u) { u.super_admin? } do
#   root 'companies#index', as: :admin_root
# end
# authenticated :user, ->(u) { !u.super_admin? && u.company.cgu_accepted_at.nil? } do
#   root 'pages#help', as: :starting_root
# end

app/models/section.rb
class Section < ApplicationRecord
  has_many :courses
  has_many :teachers, through: :courses
  has_many :students, -> { where(type: 'Student') }, class_name: 'User', foreign_key: 'section_id'
  has_many :users
  validates :name, presence: true
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :add_grade, :create_grades]

  def show
    # Assurez-vous de définir @section avant de l'utiliser pour récupérer les étudiants
    @section = Section.find(params[:id])
    @sections = current_user.sections
    @students = @section.students

    if params[:search].present?
      search_term = "%#{params[:search]}%"
      @students = @students.joins("LEFT JOIN users parents ON parents.id = users.parent_id")
                           .where("users.first_name ILIKE :search OR users.last_name ILIKE :search OR parents.first_name ILIKE :search OR parents.last_name ILIKE :search", search: search_term)
    end
    # Si params[:search] est vide ou non présent, @students contiendra déjà tous les étudiants de @section, donc aucun ajustement supplémentaire n'est nécessaire ici.
  end

  def add_grade
    @section = Section.find(params[:id])
    @sections = current_user.sections
    @students = @section.students
  end

  def show_grades
    @section = Section.find(params[:id])
    @students = @section.students
    @sections = current_user.sections
  end

  def create_grades
    course_id = params[:section][:course_id]
    exam_name = params[:section][:exam_name]
    date = params[:section][:date]

    grades_params = params[:grades].permit!.to_h

    grades_params.each do |student_id, grade_data|

      Grade.create(
        course: Course.find(course_id),
        student: Student.find(student_id),
        grade: grade_data['grade'],
        comment: grade_data['comment'],
        exam_name: exam_name,
        date: date,
      )
    end

    grades_params.each do |student_id, grade_data|

      std_id = student_id.to_i
      if params[:section]["grades[#{std_id}"].present?
        file_photo = params[:section]["grades[#{std_id}"]
        file = file_photo["photo"]["]"]
        cloudinary_response = Cloudinary::Uploader.upload(file.tempfile, folder: 'grades')
        cloudinary_url = cloudinary_response['secure_url']
      else
        cloudinary_url =""
      end

      find_grade = Student.find(student_id).grades.last
      find_grade.photo = cloudinary_url
      find_grade.save

    end
    redirect_to show_grades_section_path, notice: 'Grades were successfully created.'
  end

  private

  def set_section
    @section = Section.find(params[:id])
  end

  def grades_params
    params.require(:grades).permit(grades: [:grade, :comment, :photo])[:grades]
  end
end

app/views/sections/_calendar.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="schedule-table rounded-table">
        <table class="table bg-white rounded-table">
            <% 5.times do |i| %>
              <tr>
                <td class="schedule-table table tbody day"><%= "#{(8 + i).to_s.rjust(2, '0')}.00-#{(9 + i).to_s.rjust(2, '0')}.00" %></td>
                <% course = @courses.sample %>
                <td class="active bg-<%= course.name.downcase.gsub(' ', '-') %>"><%= course.name %> <%= @sections.sample.name %>
                  <%# <h4></h4> %>
                  <%# <p>08:05 - 08:50</p> %>
                </td>
              </tr>
            <% end %>
        </table>




        <!--
        <table class="table bg-white">
          <tbody>
            <tr>
              <td class="day">08.00-09.00</td>
              <% course = @courses.sample %>
              <td class="active bg-<%= course.name.downcase.gsub(' ', '-') %>">
                <h4><%= course.name %> <%= @sections.sample.name %></h4>
                <%# <p>08:05 - 08:50</p> %>
              </td>
            </tr>
            <tr>
              <td class="day">09.00-10.00</td>
              <% course = @courses.sample %>
              <td class="active bg-<%= course.name.downcase.gsub(' ', '-') %>">
                <h4><%= course.name %> <%= @sections.sample.name %></h4>
                <%# <p>09:05 - 09:50</p> %>
              </td>
            </tr>
             <tr>
              <td class="day">10.00-11.00</td>
              <% course = @courses.sample %>
              <td class="active bg-<%= course.name.downcase.gsub(' ', '-') %>">
                <h4><%= course.name %> <%= @sections.sample.name %></h4>
                <%# <p>10:20 - 11:00</p> %>
              </td>
            </tr>
            <tr>
              <td class="day">11.00-12.00</td>
              <% course = @courses.sample %>
              <td class="active bg-<%= course.name.downcase.gsub(' ', '-') %>">
                <h4><%= course.name %> <%= @sections.sample.name %></h4>
                <%# <p>11:15 - 12:00</p> %>
              </td>
            </tr>
          </tbody>
        </table>

        -->
      </div>
    </div>
  </div>
</div>

app/views/sections/_grades.html.erb
<div class="card-dashboard">
  <div class="card-border-top"></div>
    <div class="img" id="section-name">
      <%= section.name %>
    </div>
    <div class="bell">
      <span>
        <i class="fa-solid fa-bell"></i>
        <p class="title">
          <%= rand(2..4) %> notifications
        </p>
      </span>
    </div>
      <p class="job">
        <%= section.students.count %> Students
      </p>
</div>

app/views/sections/_grades_small.erb
<div class="card-dashboard-small <%= 'active' if section == @section %>">
  <div class="card-border-top"></div>
    <div class="img" id="section-name">
      <%= section.name %>
    </div>
</div>

app/views/sections/_notifications.html.erb
<!-- TODO: mettre ce code dans timetable
  <% hour_start = rand(24) %>
  <% hour_end = (hour_start + 1) % 24 %>
  <p class="notification-para">From <%= hour_start %>:00 to <%= hour_end %>:00</p>
-->

<div class="notif-cards">
  <div class="notification">
    <div class="notification-content">
      <% course = @courses.sample %>
      <p class="notification-title"><%= course.section.name %></p>
      <p class="notification-para1"><%= course.name %></p>
      <p class="notification-para2"><%= @notifications.sample %></p>
    </div>
  </div>
</div>

app/views/sections/_parent_announcements.html.erb
<div class="announcement mb-2">
  <h6 class="text-center bg-warning"><strong>Geography Essay</strong></h6>
  <p>Write a 1500-word essay about cultural differences between latin America and North America.</p>
</div>
<br>
<div class="announcement">
  <h6 class="text-center bg-warning"><strong>World History Presentation</strong></h6>
  <p>Prepare a 20-minute PowerPoint presentation covering at least two ancient civilizations of your choice</p>
</div>

app/views/sections/_parent_calendar.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12" id=table-round>
      <div class="schedule-table">
        <table class="table bg-white rounded-table">

        <th></th>
        <th class="text-center">Monday</th>
        <th class="text-center">Tuesday</th>
        <th class="text-center">Wednesday</th>
        <th class="text-center">Thursday</th>
        <th class="text-center">Friday</th>
          <% 5.times do |i| %>
            <tr>
              <td class="schedule-table table tbody day"><%= "#{(8 + i).to_s.rjust(2, '0')}.00-#{(9 + i).to_s.rjust(2, '0')}.00" %></td>
              <% 5.times do %>
                <% course = @courses.sample %>
                <td class="bg-<%= course.name.downcase.gsub(' ', '-') %>" ><%= course.name %></td>
              <% end %>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/sections/_todos.html.erb
<div class="notif-cards">
  <div class="notification">
    <div class="notification-content">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-3">
            <%= check_box('check', 'done', {checked: todo[:done]} ) %>
          </div>
          <div class="col-9">
            <p class="notification-para1"><%= todo[:title] %></p>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- <% 'checked' if todo[:done] %> --->

app/views/sections/add_grade.html.erb
<!-- Adaptation du formulaire d'ajout de notes avec le CSS spécifié -->

<div class="second-container">
  <div class="cards-container">
    <div class="cards-container">
    <h3 class="subtitle classes">Classes </h3 class="subtitle">
    <div id="top-cards-dashboard">
      <% @sections.each do |section| %>
        <%= link_to section_path(section) do %>
        <%= render 'sections/grades_small', section: section, active: @section %>
        <% end %>
      <% end %>
    </div>
  </div>
  </div>

  <div class="show-table-container">
    <div class="tabs">
      <%= link_to 'Classroom students', section_path(@section), class: "#{ 'active' if current_page?(section_path(@section)) }" %>
      <%= link_to 'Add a grade for this class', add_grade_section_path(@section), class: 'active', id: "add-grade-btn" %>
    </div>

    <div class="container my-5">
      <%= form_with model: @section, url: create_grades_section_path(@section), method: :post, local: true, html: { class: 'needs-validation', novalidate: '' } do |form| %>
    <div class="form-group mb-3">
      <%= form.label :course_id, 'Course', class: 'form-label w-50' %>
      <%= form.collection_select :course_id, @section.courses, :id, :name, { include_blank: 'Choose the course you want to rate' }, { class: 'form-select custom-font narrow-field' } %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :exam_name, 'Exam name', class: 'form-label' %>
      <%= form.text_field :exam_name, placeholder: 'Name of the exam you want to rate', class: 'form-control narrow-field' %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :date, 'Date of exam', class: 'form-label' %>
      <%= form.date_field :date, class: 'form-control narrow-field' %>
    </div>

        <div class="table-responsive">
          <table class="table table-hover rounded-table small-mg">
            <thead>
              <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Grade</th>
                <th>Comment</th>
                <th>Add Exam file</th>
              </tr>
            </thead>
            <tbody>
              <% @section.students.each_with_index do |student, index| %>
              <tr>
                <td><%= student.first_name %></td>
                <td><%= student.last_name %></td>
                <td>
                  <%= number_field_tag "grades[#{student.id}][grade]", nil, placeholder: 'Grade must be between 1 and 6', class: 'form-control', min: 1, max: 6 %>
                </td>
                <td>
                  <%= text_area_tag "grades[#{student.id}][comment]", nil, class: 'form-control' %>
                </td>
                <td>
                  <%= form.file_field "grades[#{student.id}][photo]", class: 'form-control' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <div class="form-actions d-flex justify-content-end mt-3">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <%= link_to 'Cancel', section_path(@section), class: 'btn btn-secondary me-2' %>
          <%= form.submit 'Submit', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/sections/grades_dashboard_teacher.html.erb
<div class="show-classes-container">
  <div class="cards-container d-flex justify-content-around pt-3">
    <h2><%=@student.first_name%>'s Grades</h2>
    <h4>Class : <%=@section.name%></h4>
  </div>
  <div class="show-table-container me-4">
    <div class="tabs">
      <div class="d-flex justify-content-between pe-5">
        <h4>Grades</h4>
        <h4>Averages</h4>
      </div>
    </div>

      <div class="student-list d-flex">
        <table class="me-2">
          <thead>
            <tr>
              <th>Course Name</th>
              <th>1</th>
              <th>2</th>
              <th>3</th>
              <th>4</th>
              <th>5</th>
              <th>6</th>
              <th>7</th>
            </tr>
          </thead>
        <tbody>
          <% @grades_by_course.each do |course, grades| %>
            <tr>
              <td><%= course.name %></td>
              <% grades.each do |grade| %>
                <td><%= grade.grade%></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
        </table>
      <table class="me-1" style="width: 120px;">
        <thead>
          <tr>
            <th>Student</th>
          </tr>
        </thead>
        <tbody>
          <% @averages_by_course.each do |course, average_grade|%>
            <tr>
              <td><%=average_grade%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <table style="width: 120px;">
        <thead>
          <tr>
            <th>Class </th>
          </tr>
        </thead>
        <tbody>
          <% @grades_by_courses.each do |course, average_grade|%>
            <tr>
              <td><%=average_grade%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/sections/show.html.erb
<div class="second-container">
  <div class="cards-container">
    <h3 class="subtitle classes">Classes </h3 class="subtitle">
      <div id="top-cards-dashboard">
        <% @sections.each do |section| %>
          <%= link_to section_path(section) do %>
          <%= render 'sections/grades_small', section: section, active: @section %>
          <% end %>
        <% end %>
      </div>

  </div>
    <div class="show-table-container">
    <div class="tabs">
      <%= link_to 'Classroom students', section_path(@section), class: "#{ 'active' if current_page?(section_path(@section)) }" %>
      <%= link_to 'Add a grade for this class', add_grade_section_path(@section), id: "add-grade-btn" %>
    </div>



    <%= form_tag(section_path(@section), method: :get, class: "input-group") do %>
      <div class="input">
        <%= text_field_tag :search, params[:search], id: "search-input", autocomplete: "off", class: "form-control", placeholder: "Enter a name" %>
      </div>
      <div class="input">
        <%= button_tag(type: 'submit', class: "form-control", id: "submit-search") do %>
          Search
        <% end %>
      </div>
    <% end %>

    <div>
      <% if @students.count == 1 %>
        <p><%= @students.count %> student found</p>
      <% elsif @students.count == 0 %>
        <p>No results for this seach</p>
      <% else %>
        <p><%= @students.count %> students</p>
      <% end %>
    </div>
  <!-- Student list -->
<div class="student-list">
  <table class="table table-hover rounded-table">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Parent Name</th>
        <th>Phone Number</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.first_name %></td>
          <td><%= student.parent&.last_name %></td>
          <td><%= student.parent&.first_name %> <%= student.parent&.last_name %></td>
          <td>
            <span style="display: inline-flex; align-items: center;">
              <%= student.parent.phone_number %>
              <i class="fa-solid fa-phone" style="margin-left: 7px;"></i>
            </span>
          </td>
          <td>
            <span style="display: inline-flex; align-items: center;">
                <%= student.parent.email %>
              <i class="fa-solid fa-envelope" style="margin-left: 7px;"></i>
            </span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/sections/show_grades.html.erb
<div class="second-container">
  <div class="cards-container">
    <h3 class="subtitle classes">Class <%=@section.name%> / Grade Averages</h3 class="subtitle">
    </div>
  <div class="show-table-container">
  <div class="cards-container">
    <h3 class="subtitle classes">Classes </h3 class="subtitle">
    <div id="top-cards-dashboard">
      <% @sections.each do |section| %>
        <%= link_to show_grades_section_path(section) do %>
        <%= render 'sections/grades_small', section: section, active: @section %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="tabs">
    <!-- Exemple pour Classroom Students (Assumant que c'est la page index des sections) -->
    <%= link_to 'Classroom students', section_path(@section), class: "#{ 'active' if current_page?(section_path(@section)) }" %>
    <%= link_to 'Add a grade', add_grade_section_path(@section), id: "add-grade-btn" %>
  </div>
  <br>

  <!-- Student list -->
    <div class="student-list">
      <table class="table table-hover rounded-table">
        <thead>
          <tr>
            <th>Student Name</th>
            <% @section.courses.each do |course| %>
            <th><i class="<%= course.icon %>"></i> <%= course.name %></th>
            <% end %>
            <th class="text-center">Student Average</th>
          </tr>
        </thead>
        <tbody>
          <% @section.students.each do |student| %>
            <tr>
              <td>
                <%= link_to "#{student.first_name} #{student.last_name}", student_path(student), class: 'text-decoration-underline', style: 'color: black;' %>
              </td>
              <% @section.courses.each do |course| %>
                <% grades = student.grades.where(course_id: course.id) %>
                <% course_average = grades.average(:grade)&.round(1) %>
                <% case course_average %>
                  <% when 1.0..1.4 %>
                    <td><a class="bg-one text-white p-2 rounded text-center text-decoration-none"><%= course_average %></a></td>
                  <% when 1.5..1.9 %>
                    <td><a class="bg-one-half text-white p-2 rounded text-center text-decoration-none"><%= course_average %></a></td>
                  <% when 2.0..2.4 %>
                    <td><a class="bg-two text-white p-2 rounded text-center text-decoration-none"><%= course_average %></a></td>
                  <% when 2.5..2.9 %>
                    <td><a class="bg-two-half text-white p-2 rounded text-center text-decoration-none"><%= course_average %></a></td>
                  <% when 3.0..3.4 %>
                    <td><a class="bg-three text-white p-2 rounded text-center text-decoration-none"><%= course_average %></a></td>
                  <% when 3.5..3.9 %>
                    <td><a class="bg-three-half text-white p-2 rounded text-center text-decoration-none"><%= course_average %></a></td>
                  <% when 4.0..4.4 %>
                    <td><a class="bg-four text-white p-2 rounded text-center text-decoration-none"><%= course_average %></a></td>
                  <% when 4.5..4.9 %>
                    <td><a class="bg-four-half text-white p-2 rounded text-center text-decoration-none"><%= course_average %></a></td>
                  <% when 5.0..5.4 %>
                    <td><a class="bg-five text-white p-2 rounded text-center text-decoration-none"><%= course_average %></a></td>
                  <% when 5.5..5.9 %>
                    <td><a class="bg-five-half text-white p-2 rounded text-center text-decoration-none"><%= course_average %></a></td>
                  <% when 6.0 %>
                    <td><a class="bg-six text-white p-2 rounded text-center text-decoration-none"><%= course_average %></a></td>
                  <% else %>
                    <td><%= course_average %> LO</td>
                <% end %>
              <% end %>
              <% class_average = student.grades.average(:grade)&.round(1) %>
              <td class="text-center fw-bold"><%= class_average if class_average %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>
</div>